/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "sans-serif"],
      },
      keyframes: {
        "slide-up": {
          from: { transform: "translateY(100%)" },
          to:   { transform: "translateY(0)" },
        },
      },
      animation: {
        "slide-up": "slide-up 0.3s cubic-bezier(0.32, 0.72, 0, 1)",
      },
      colors: {
        "surface-container": "#edeee8",
        "inverse-on-surface": "#f0f1ea",
        "surface-variant": "#e2e3dc",
        "on-surface": "#1a1c18",
        "primary-container": "#6a69cc",
        "on-secondary-container": "#763f00",
        "on-surface-variant": "#464552",
        "on-secondary": "#ffffff",
        "surface": "#f9faf3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4ed",
        "surface-dim": "#d9dbd4",
        "on-error": "#ffffff",
        "secondary": "#8d4f0e",
        "on-background": "#1a1c18",
        "outline-variant": "#c7c5d4",
        "on-primary": "#ffffff",
        "inverse-primary": "#c2c1ff",
        "surface-container-high": "#e8e9e2",
        "on-primary-fixed-variant": "#3b399a",
        "background": "#f9faf3",
        "on-secondary-fixed": "#2e1500",
        "secondary-container": "#feac66",
        "surface-container-highest": "#e2e3dc",
        "error": "#ba1a1a",
        "on-primary-fixed": "#0b006b",
        "inverse-surface": "#2f312d",
        "tertiary-container": "#268083",
        "secondary-fixed": "#ffdcc2",
        "on-primary-container": "#fffbff",
        "primary-fixed-dim": "#c2c1ff",
        "primary-fixed": "#e2dfff",
        "outline": "#777683",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "primary": "#5150b1",
        "tertiary": "#006769",
        "on-tertiary-container": "#f3ffff",
        "inverse-on-surface": "#f0f1ea",
      },
      borderRadius: {
        card: "24px",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "card-padding": "24px",
        "stack-gap": "16px",
        "container-margin": "20px",
        gutter: "12px",
      },
    },
  },
  plugins: [],
};